spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digitalmarket
    username: digitalmarket
    password: digitalmarket
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update