spring:
  datasource:
    url: jdbc:postgresql://192.168.1.103:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update